### PR TITLE
Make ² and ⁻ work with lists

### PR DESCRIPTION
**Pull request by Fmbalbuena**

### CODE REVIEW

**Review by lyxal — CHANGES_REQUESTED** [review]
These are supposed to vectorise by default. Making them act on the entire list is not desired behaviour.

**Comment by ysthakur** [comment]
@Fmbalbuena Specifically, the implementations need to use `addPartVect` instead of `addPart` (to vectorize as lyxal said). No other changes are needed

**Comment by AMiller42** [comment]
@ysthakur If these are supposed to vectorise by default, then I don't believe any changes are needed.

[Try it Online!](https://vyxal.github.io/latest.html#WyIiLCIiLCIjW1wiYWJjZFwifFwiZWZnaFwifDY5fDQyMCNdwrIiLCIiLCIiLCIzLjIuMCJd)

**Comment by ysthakur** [comment]
Oh, interesting, I thought addPart didn't handle that

**Comment by ysthakur** [comment]
Closing since the current behavior already matches the intended behavior

**Pull request closed without merging**
