### PR TITLE
Add multiline comments

### LINKED ISSUE #876: Block comments?
Just would be nice to have. Maybe `#{...}#`?

### PR DESCRIPTION
**Pull request by Steffan153**
`#{` and `#}`. Also removes a few unused imports.

(The branch name and commit name, I just wasn't thinking)

Next we need to work on Vylight to add support for this.

Closes #876.

### CODE REVIEW

**Review by Lyxal — APPROVED** [review]
Lgtm

**Comment by chunkybanana** [comment]
*sighs* I'll update Vylight next week

**Review by chunkybanana — APPROVED** [review]
More tests would be appreciated.

**Comment by Steffan153** [comment]
No, I'll update Vylight. :)

**Pull request merged**
