### PR TITLE
Add `~` flag for testing against expected output

### LINKED ISSUE #1307: Add another flag to run test cases with expected output
So the format would now require a tuple with two elements, where the first is the list of input(s), and the second is the expected.

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #1307

### CODE REVIEW

**Comment by Lyxal** [comment]
The flag choice (currently `~`) and output format for test cases is subject to change.

**Review by Steffan153 — DISMISSED** [review]

**Review by Steffan153 — COMMENTED** [review]
Can you use the emojis ✅❌ at the end for a quick look? My test suites usually do that, along with aligned space so all the emojis line up

**Comment by Steffan153** [comment]
[Try it online!](https://tio.run/##PY9NboMwEIX3PsWIje3GIBtoGoLci1RdmNYoSATMzwJEWXbXI7SXy0Xo4Cpd@c33nt/Ybh4vbZNspa7NtXg3YERxNofiQ21l28MMVQOtsw2T/Ex2U8/RMPaVYzwaXF2NjEL4DJTnk5j11ThWNaMwd09Qzgn0dtAlwwDPUQTLtApY5jXIO5zw9oKBNSDw1vYayxmOXOsit7qkzE4ugqVYOX1gKsQIFroet7ABDkBhx6ewxicOnCPp/qn0tPPU3mn8R62n9Pbzdfv@pC9Y@8q3LRbx/puUZELtQkmiMvGY7vopIUpKKTKVeAtPolR2kiJJj57ESXz8BQ "Python 3 – Try It Online")

**Comment by Steffan153** [comment]
Idc

**Comment by Lyxal** [comment]
> Idc

Well which do you prefer?

**Comment by Steffan153** [comment]
Neither, whichever you do

**Pull request merged**
