### PR TITLE
Add `)` as lambda to newline, and make only `}` close all structures

### LINKED ISSUE #1342: Add lambda to newline
We can use `)`, so if no `(` is opened, then it does lam to newline

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #1342

### CODE REVIEW

**Review by Steffan153 — CHANGES_REQUESTED** [review]
Keep the rest of the closing characters functioning as before.

**Review by Steffan153 — CHANGES_REQUESTED** [review]
This still isn't how it was before - `}];` should not necessarily close *all* structures, so `[{(...}` will only close the for-loop.

**Comment by chunkybanana** [comment]
^

**Review by Steffan153 — APPROVED** [review]
👍

**Pull request merged**
