### PR TITLE
literally what the branch says

### LINKED ISSUE #495: `T` doesn't set a function's arity to 3
https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxIDIgMyDOuys7IFQiLCIiLCIiXQ==

Yes this was my fault

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #495

### CODE REVIEW

**Review by chunkybanana — APPROVED** [review]

**Review by cgccuser — DISMISSED** [review]
👍but can you add a testcase?

**Comment by chunkybanana** [comment]
> 👍but can you add a testcase?

ಠ_ಠ function testcasen't.

**Comment by Lyxal** [comment]
> 👍but can you add a testcase?

Tell me how tf you gonna test case a function?

**Review by cgccuser — APPROVED** [review]
I'm approving this, but you do realize you can manually add tests too, right? Just put it in a different file called `test_specific.py` or something.

**Pull request merged**
