### PR TITLE
Update Production (14/04/2022)

### PR DESCRIPTION
**Pull request by AMiller42**
Merge after:
- [x] #847 
- [x] #852

### CODE REVIEW

**Comment by chunkybanana** [comment]
Woah, you can tag PRs now?

**Comment by Lyxal** [comment]
I thought it's always been a thing and that we just never used it.

I'm all for PR tagging though

**Comment by Steffan153** [comment]
Yeah it's no new feature, lol

**Comment by AMiller42** [comment]
Yeah, I figured at the very least we might as well tag production PRs just for organization's sake

**Review by Steffan153 — APPROVED** [review]

**Comment by Steffan153** [comment]
Should we squash?

**Pull request merged**
