### PR TITLE
Add ¨" element and allow (str,list) as args for β

### PR DESCRIPTION
**Pull request by PlaceReporter99**
Much easier to implement digraphs in the string compression utility!

### CODE REVIEW

**Comment by PlaceReporter99** [comment]
Do I add the test to the element test file or create a separate file @Lyxal

**Comment by Lyxal** [comment]
To the yaml file - make sure to add a description of what the new element does.

**Comment by Lyxal** [comment]
elements.yaml specifically. Don't add it to the test file manually because that file is automatically generated

**Comment by PlaceReporter99** [comment]
@Lyxal finished

**Comment by Lyxal** [comment]
I think I might extend this PR to also make the new digraph parse json structures. That's a feature that's been suggested before and could actually be pretty cool.

**Comment by PlaceReporter99** [comment]
@Lyxal i think something went wrong with one of your checks

**Comment by PlaceReporter99** [comment]
@Lyxal i think `øJ` already parses json.

**Comment by Lyxal** [comment]
> @Lyxal i think `øJ` already parses json.

Ah, so it does.

**Review by Lyxal — APPROVED** [review]

**Review by Lyxal — CHANGES_REQUESTED** [review]
The test case `["abcaabac",["a","bc","ac","b"]] : ["a","bc","a","a","b","ac"]` doesn't make sense - the first `bc` will always be treated as `b` instead of `bc` because `re.match` gets the shortest match.

That's why the test was not finishing. It was in an infinite loop.

**Comment by PlaceReporter99** [comment]
@Lyxal running it in the ide, the problem is the last `c` isn't matched.

**Comment by PlaceReporter99** [comment]
Well it’s returning the correct value for that now but it’s claiming invalid types were given…

**Comment by Lyxal** [comment]
I needed to rename the branch for git purposes. This PR is now #1833

**Pull request closed without merging**
