### PR TITLE
Add tab completions for unicode chars

### PR DESCRIPTION
**Pull request by Steffan153**
Type a 2-character alias, and press Tab.

### CODE REVIEW

**Comment by Steffan153** [comment]
https://user-images.githubusercontent.com/40404519/178049066-542963be-052e-4fed-b5af-da8d4e1028cc.mp4

**Comment by cjquines** [comment]
this is such a pleasant change

**Comment by chunkybanana** [comment]
Wow, cool!

**Review by chunkybanana — APPROVED** [review]
This is gonna be very useful. We might want to update teh list at some point

**Pull request merged**
