### PR TITLE
Add non-modular indexing

### PR DESCRIPTION
**Pull request by Lyxal**
I swear there's been cases where it's been a problem to not have non-modular indexing

### CODE REVIEW

**Review by Steffan153 — CHANGES_REQUESTED** [review]
Erroring is extremely unuseful in code golf. You should return something else like `0`.

**Comment by Lyxal** [comment]
> Erroring is extremely unuseful in code golf. You should return something else like `0`.

That would be a different overload then. I want something that _does_ error. Even if it's not useful.

**Comment by Lyxal** [comment]
I also wanted something that explicitly disrupts control flow/easily tells you if the index was out of bounds. Returning 0 if out of bounds doesn't easily tell you if the index was out of bounds because you may have gotten a 0 out of the list.

**Comment by Lyxal** [comment]
if ind > length: return "invalid input" or something like that

**Comment by Lyxal** [comment]
It may not be the most useful or golfy thing, but it's something I want to be a thing in version 2

**Review by Steffan153 — APPROVED** [review]
Fine

**Pull request merged**
