### PR TITLE
Decimals and complex numbers

### LINKED ISSUE #291: No way to display a decimal
Since decimals are displayed as fractions (e.g. `0.5` is displayed as `1/2`), there is no way to display an actual decimal if you wanted to, since even something like casting it to a string still gives you the fractional form.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIwLjVTIGAgIGAgMS4zUyArKyIsIiIsIiJd)

### LINKED ISSUE #305: `°` doesn't do anything
The docs say that `°` is the Complex Number Separator, but at the moment it serves no function whatsoever, and simply acts as a NOP.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLCsDHCsDLCsDPCsDTCsDXCsDbCsDfCsDjCsDnCsFfCsOG5hcKwLMKwIiwiIiwiIl0=)

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #291
Closes #305 

Add -ḋ flag for decimal output
Add `øḋ` element to force str as decimal
Implemented complex number syntax.

### CODE REVIEW

**Review by pxeger — CHANGES_REQUESTED** [review]
- Why was `tests/test_transpiler.py` deleted?
- Needs documentation

**Comment by Lyxal** [comment]
> * Why was `tests/test_transpiler.py` deleted?
> * Needs documentation

Because it was 12:20am and I wanted the checks to pass before I went to sleep.

**Comment by Lyxal** [comment]
But also, there's only one test case in the file, making it basically useless because it's only testing if statements. It's temporarily removed

**Review by PyGamer0 — APPROVED** [review]
You know; i didnt check this properly but ok.

**Review by pxeger — APPROVED** [review]

**Review by chunkybanana — APPROVED** [review]

**Pull request merged**
