### PR TITLE
paramemter -> parameter

### PR DESCRIPTION
**Pull request by ysthakur**
paramemter -> parameter

This has to be the stupidest PR in all history

### CODE REVIEW

**Review by pxeger — APPROVED** [review]

**Review by PyGamer0 — APPROVED** [review]
oof

**Comment by Lyxal** [comment]
Nothing quite like overformalising a spelling mistake

**Comment by ysthakur** [comment]
@Lyxal Can't help it, fb's protected so I need a proper PR for a single commit.

**Comment by Lyxal** [comment]
I understand lol. I almost had to get two reviews to just update the style guide.

**Pull request merged**
