### PR TITLE
Add several "all powers" built-ins

### LINKED ISSUE #1419: All powers of a number
Like `¨*` but with `e` if that makes sense. Also, common powers like 2, 3, 10 should have their own digraph

(created by lyxal [here](https://chat.stackexchange.com/transcript/message/61925167))

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #1419

### CODE REVIEW

**Review by Steffan153 — COMMENTED** [review]
Not sure if all powers of 3 is useful but whatever. Why isn't this under list digraphs?

**Comment by Lyxal** [comment]
> Not sure if all powers of 3 is useful but whatever. Why isn't this under list digraphs?

I placed it in the miscellaneous digraph space for consistency with all multiples.

Do you think there's a power more suitable than 3? If so, it can be changed to that. I just thought 3 was a sensible one to have.

**Review by Steffan153 — APPROVED** [review]
No, I think `3` just isn't needed

**Comment by Lyxal** [comment]
Fair enough. I'll remove it a little bit later

**Pull request merged**
