### PR TITLE
Version 2: Add numeric overloads for G and g

### LINKED ISSUE #1486: Number overload to `g` and `G`
Either operate on digits (which is arguably useless) or do something else

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #1486

### CODE REVIEW

**Comment by Lyxal** [comment]
https://chat.stackexchange.com/transcript/message/63231669#63231669

**Review by Steffan153 — COMMENTED** [review]
Literally extremely useless.

**Comment by Lyxal** [comment]
Round to nearest power of 10 isn't useless. It's got applications.

**Review by chunkybanana — COMMENTED** [review]
^^

**Comment by Lyxal** [comment]
Well if it's so useless why don't y'all suggest something instead?

**Review by GingerIndustries — COMMENTED** [review]
Insufficiently funky

**Comment by Steffan153** [comment]
> Round to nearest power of 10 isn't useless. It's got applications.

Digraph. It's not something you use much.

**Comment by Steffan153** [comment]
`∆K` and `∆²` are common enough according to the corpus. How about those?

**Comment by Lyxal** [comment]
They'll be made NOPs for the time being

**Pull request closed without merging**
