### PR TITLE
Update deploy-pages.yaml

### PR DESCRIPTION
**Pull request by Steffan153**

### CODE REVIEW

**Review by Lyxal — APPROVED** [review]

**Comment by ysthakur** [comment]
Why?

**Comment by ysthakur** [comment]
@Steffan153 @Lyxal What is this for?

**Comment by Lyxal** [comment]
```
2023-02-11T01:18:04.6840987Z ##[group]Run mkdir pages
2023-02-11T01:18:04.6896063Z ##[endgroup]
2023-02-11T01:18:04.6981013Z mkdir: cannot create directory ‘pages’: File exists
```

**Comment by ysthakur** [comment]
Oh, the `mkdir pages` line should be removed then. Previously, we didn't already have a `pages` directory with everything in it

**Pull request merged**
