### PR TITLE
Make `vy_exec` vectorise properly on strings.

### LINKED ISSUE #851: Executing a list of strings recursively vectorises
The `Ė` command has a helper function that will either return the reciprocal of a value if it is number, or vectorise itself over the value otherwise. The command only checks once if the value is a string, so if the string is wrapped in a list, it recursively vectorises the helper function over the value until it hits the recursion limit.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLin6hgYWDin6kgxJYiLCIiLCIiXQ==)

### PR DESCRIPTION
**Pull request by Lyxal**
Fixes #851

### CODE REVIEW

**Comment by AMiller42** [comment]
The strings inside of the lists don't have access to the stack, and will instead take input. Not sure if that should be changed or not, but it is something to be aware of. It could potentially be useful, since it kind of acts like a lambda with no arguments, except that it can take implicit input.

Example:
```
Input: 69

1 2 3 `d`wĖ

Output: ⟨ 138 ⟩
```

**Comment by chunkybanana** [comment]
Could it act like `₍`?

**Review by cgccuser — APPROVED** [review]

**Review by Steffan153 — APPROVED** [review]

**Comment by cgccuser** [comment]
I think the current behavior is fine. It'd be a pain to change it anyway.

**Comment by Steffan153** [comment]
Should we merge?

**Pull request merged**
