### PR TITLE
Add discord link

### PR DESCRIPTION
**Pull request by Tams-Tams**
Just added the server link to the readme. Is a pr okay for something small like this?

### CODE REVIEW

**Review by pxeger — CHANGES_REQUESTED** [review]
Unless this is an official discord server, I don't think this should be merged (and FWIW, I don't think we should have an official discord server. The SE chat room is good enough, and having two chat rooms will fragment discussion for no reason).

**Comment by cgccuser** [comment]
@pxeger I'm pretty sure it's the "official" server, and hyper may make a bridge, reducing the fragmentation. Discord is more convenient for people outside SE.

**Review by cgccuser — APPROVED** [review]

**Comment by Lyxal** [comment]
@pxeger fragmentation and a lack of need of a discord server has been why I've held off on making one for so long.

But @cgccuser is right in saying discord is more convenient for those not on SE - it could help bring people from numerous esolang focused servers into vyxal

**Review by chunkybanana — APPROVED** [review]

**Comment by Tams-Tams** [comment]
@Lyxal Are there actually people who came across Vyxal, who're not on SE?

**Comment by Lyxal** [comment]
@Tams-Tams there is - people from other discord servers I'm on know about Vyxal

**Pull request merged**
