### PR TITLE
Add four argument vectorization for one and two lists

### PR DESCRIPTION
**Pull request by Steffan153**
Not sure what to do for three & four lists yet...

### CODE REVIEW

**Comment by Steffan153** [comment]
So...

- Behavior was changed for three-list vectorization to do `zip(a, b, c)`
- Four argument vectorization added
- `¨v` added for simple vectorization

**Review by Lyxal — APPROVED** [review]
Looks good to me!

**Comment by chunkybanana** [comment]
We really need to fix those failing tests

**Comment by Steffan153** [comment]
Yeah it's blocking merge on everything

**Review by Seggan — APPROVED** [review]
Code nesting galore! Hope you have Copilot 😅

**Pull request merged**
