### PR TITLE
Make vectorised recursion (`vx`) work again

### PR DESCRIPTION
**Pull request by Steffan153**
makes the transpiler use the function_stack instead of this

#857 broke this, btw.

### CODE REVIEW

**Comment by chunkybanana** [comment]
Make some tests plz

**Comment by chunkybanana** [comment]
***MAKE SOME TESTS PLZ***

**Comment by Steffan153** [comment]
Btw the reason I haven't added tests yet is because it doesn't work atm

**Comment by Steffan153** [comment]
Alr yay this works now let's add tests now

**Review by chunkybanana — APPROVED** [review]

**Review by Lyxal — APPROVED** [review]

**Pull request merged**
