### PR TITLE
Make `ḋ` work on infinite lists

### LINKED ISSUE #699: `ḋ` doesn't work on infinite lists
# [Vyxal](https://github.com/Vyxal/Vyxal), 4 bytes
```
Þp3ḋ
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCLDnnAz4biLIiwiIiwiIl0=)

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #699

### CODE REVIEW

**Comment by Lyxal** [comment]
Why not use itertools? Because it tries to get the length of lists before generating combinations. And obviously, taking the length of an infinite list will never halt.

**Comment by chunkybanana** [comment]
While functional, this is quite inefficient.

**Comment by Lyxal** [comment]
That do be how it is sometimes.

**Review by chunkybanana — APPROVED** [review]

**Comment by cgccuser** [comment]
My commit (#707) is bigger than yours LMAO

**Pull request closed without merging**
