### PR TITLE
Fixed mold (I think?)

### PR DESCRIPTION
**Pull request by chunkybanana**
This should work without mutable lists. All tests work.

### CODE REVIEW

**Comment by chunkybanana** [comment]
Should also work for infinite lists. Some small modifications may be required for it to work for modular indexing.

**Comment by chunkybanana** [comment]
Btw, helps fix #1119

**Review by Lyxal — APPROVED** [review]
:+1:

**Review by cgccuser — APPROVED** [review]
Awesome job

**Pull request merged**
