### PR TITLE
Testing go yee

### LINKED ISSUE #1613: Exciting Test Issue Yay
Spingle My Dingle

### PR DESCRIPTION
**Pull request by GingerIndustries**
Closes #1613.

### CODE REVIEW

**Review by Lyxal — CHANGES_REQUESTED** [review]
Amogus

**Review by chunkybanana — COMMENTED** [review]
kinda sus ngl

**Review by Lyxal — CHANGES_REQUESTED** [review]
Needs more egg

**Review by Lyxal — CHANGES_REQUESTED** [review]
Have some more chicken

Have some more pie

It doesn't matter if it's boiled or fried

**Pull request closed without merging**
