### PR TITLE
Fix `~` flag not working with other flags

### LINKED ISSUE #1703: Bug: The `~` flag doesn't work with other flags
The `A` flag does, so why doesn't the `~` flag?

See [this program](https://vyxal.pythonanywhere.com/#WyJ+cyIsIiIsIiIsIiIsIlsxLCAyLCAzXSA9PiA2XG5bMywgNCwgNV0gPT4gMTIiXQ==). Its equivalent [`A` flag version](https://vyxal.pythonanywhere.com/#WyJBcyIsIiIsIiIsIiIsIlsxLCAyLCAzXSAjPT4gNlxuWzMsIDQsIDVdICM9PiAxMiJd) works.

### PR DESCRIPTION
**Pull request by nayakrujul**
Let's see how this goes...

Fixes #1703

### CODE REVIEW

**Comment by nayakrujul** [comment]
@Lyxal Can you test that?

**Comment by Lyxal** [comment]
I will when I get the chance. I'm currently on mobile and away from my computer.

**Comment by Lyxal** [comment]
I think this works, but I'd like to get some reviews from @ysthakur and @Steffan153 also because it's always good to have extra sets of eyes that have had previous experience with this sort of stuff.

**Comment by Lyxal** [comment]
image

**Comment by nayakrujul** [comment]
Nice!

**Comment by Lyxal** [comment]
```
PS .../vyxal>  python -m vyxal " " "e~s" "[1, 2, 3] => 6" "[3, 4, 5] => 12"
([1, 2, 3] => 6) ==> PASS ✅
([3, 4, 5] => 12) ==> PASS ✅
PS .../vyxal>  python -m vyxal "+" "e~s" "2, 3 => 5" "4, 5 => 12"
(2, 3 => 5) ==> PASS ✅
(4, 5 => 12) ==> FAIL ❌ (expected 12, got 9)
```

**Pull request merged**
