### PR TITLE
Document `∆I` and `¨ẇ`

### LINKED ISSUE #859: ∆I, øF, and ¨ẇ undocumented
(created by Steffan [here](https://chat.stackexchange.com/transcript/message/60901065))

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #859

- `øF` isn't documented because it was more of a joke and should probably be removed.

### CODE REVIEW

**Comment by Seggan** [comment]
What does `øF` do, exactly?

**Comment by chunkybanana** [comment]
Ah yes, øF, the factorial element that vectorises over strings. such helpful.

**Review by Seggan — APPROVED** [review]
/shrug

**Comment by chunkybanana** [comment]
IIRC it's a joke thing generated by copilot

**Pull request merged**
