### PR TITLE
Make sure to cast the result of integration to string

### PR DESCRIPTION
**Pull request by Lyxal**

### CODE REVIEW

**Review by cgccuser — COMMENTED** [review]
Wait, what if you need it to be a number? Could we instead check if it can be converted to a number and only cast to string if not?

**Comment by Lyxal** [comment]
> Wait, what if you need it to be a number? Could we instead check if it can be converted to a number and only cast to string if not?

Integration is a string overload.

**Comment by cgccuser** [comment]
Right, but the result can also be a number instead of a symbolic thingy, right?

**Comment by Lyxal** [comment]
Very rarely will the result of integration be a number. And even still, it's best to keep it as a string for consistency.

**Review by chunkybanana — APPROVED** [review]

**Review by chunkybanana — APPROVED** [review]

**Review by PyGamer0 — APPROVED** [review]

**Pull request merged**
