### PR TITLE
Move the philosophy stuff into a different repo

### PR DESCRIPTION
**Pull request by Lyxal**

### CODE REVIEW

**Comment by Seggan** [comment]
Why?

**Comment by chunkybanana** [comment]
^

**Review by PyGamer0 — APPROVED** [review]

**Comment by Lyxal** [comment]
They feel unnecessary now and also I feel like they aren't exactly genuine because I got AI to write them. Also, it feels as if though these documents would be better suited as a sort of universal organisation thing rather than language specific. 


I plan to rewrite them one day in the future. But for now, they're better not in the main repo.

**Comment by Seggan** [comment]
If it is destined to get a rewrite soon™, then why move it instead of rewrite?

**Review by cgccuser — APPROVED** [review]
Not having these in the main repo is a good call

**Pull request merged**
