### PR TITLE
Add ¨* (all multiples) element

### LINKED ISSUE #767: All multiples diagraph
Diagraph returning an infinite LazyList of multiples of a number `a`.

```
- element: TBD
  name: All Multiples
  description: Return all multiples of a
  arity: 1
  overloads:
    num: [a*1, a*2, a*3, a*4, ...]
  vectorise: true
```

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #767

### CODE REVIEW

**Comment by Lyxal** [comment]
man, the pre-commit check really doesn't like me tonight.

**Review by cgccuser — APPROVED** [review]
I feel like these digraphs might be getting a little too specific but lgtm

**Comment by cgccuser** [comment]
On second thought, it’s not too specific

**Review by AMiller42 — APPROVED** [review]
lgtm

**Pull request merged**
