### PR TITLE
Add replace nth occurrence digraph

### PR DESCRIPTION
**Pull request by Steffan153**

### CODE REVIEW

**Review by cgccuser — APPROVED** [review]
Great work, and thanks for adding tests! Btw, you can remove some of them and only keep the ones that are edge cases

**Review by Lyxal — APPROVED** [review]
Wowie a quadgraph. Never seen one of those before. Very cool.

**Comment by cgccuser** [comment]
Wait a second, have we implemented vectorization for tetrads? It only goes up to triads right? @Lyxal

**Comment by Lyxal** [comment]
That's a good point. I don't know how you'd even do 4 argument vectorisation.

**Comment by Steffan153** [comment]
this element shouldn't need to vectorize though.

**Comment by Lyxal** [comment]
User means how is it handled if `v` is used with it.

**Comment by Steffan153** [comment]
oh, yeah. it shouldn't be hard to implement it. just need a bit of ~~elbow~~ keyboard grease.

**Pull request merged**
