### PR TITLE
Implement a basic set of flags for version 3

### LINKED ISSUE #1987: Explicit output doesn't disable implicit output
Ruhroh

### PR DESCRIPTION
**Pull request by lyxal**
Closes #1987

### CODE REVIEW

**Comment by lyxal** [comment]
Okay so what I've tried to do is make it so that an empty program will print the input.

I removed the `if the stack is empty` check before printing.

But now it's erroring. To be investigated.

**Comment by ysthakur** [comment]
What's the error? It doesn't get the next input if the stack is empty?

**Comment by lyxal** [comment]
> What's the error? It doesn't get the next input if the stack is empty?

You can see the error in the test workflow run.

**Comment by ysthakur** [comment]
> You can see the error in the test workflow run.

I think that's just because it now uses `ctx.pop()` instead of `ctx.peek`. Not sure if pop's behavior makes it more desirable, though

**Comment by lyxal** [comment]
> > You can see the error in the test workflow run.
> 
> I think that's just because it now uses `ctx.pop()` instead of `ctx.peek`. Not sure if pop's behavior makes it more desirable, though

This is intentional

**Pull request merged**
