### PR TITLE
Increment decrement until false monographs

### LINKED ISSUE #935: `∆›` and `∆‹` can (should) be single characters
We have plenty of space for function overloads, so we may as well give these single-character versions.

### PR DESCRIPTION
**Pull request by Steffan153**
Closes #935

### CODE REVIEW

**Comment by Steffan153** [comment]
whoops how did those commits from 932 get in there

**Comment by Steffan153** [comment]
What in the world

**Review by Lyxal — APPROVED** [review]

**Review by cgccuser — APPROVED** [review]
Might want to remove the old elements entirely but it doesn't hurt to keep them around, I guess

**Comment by Steffan153** [comment]
It would break old code if we removed them. We can remove in v3

**Pull request merged**
