### PR TITLE
Add string interpolation

### LINKED ISSUE #1073: Add string interpolation
Basically we need to find a character that's not yet used by the short dictionary, and every time it is used in a string, it will pop from the stack and interpolate. (This can be done now, not in v3.)

### PR DESCRIPTION
**Pull request by Steffan153**
Closes #1073

### CODE REVIEW

**Review by Seggan — APPROVED** [review]

**Comment by Seggan** [comment]
This is gonna be harder in Myxal

**Review by chunkybanana — CHANGES_REQUESTED** [review]
We need to remove `Π` from the compression dictionary

**Comment by Steffan153** [comment]
It can still be used as a second character, like `∑Π`, but it's not currently used as a first character. I will remove that

**Comment by Steffan153** [comment]
But that's gonna be a *pain* to change to make it never be used as a first character, but still as a second to not break old code. The dictionary probably won't be changed in v2 to be big enough to use `Π` anyway...

**Review by cgccuser — APPROVED** [review]
Nice feature

**Review by chunkybanana — APPROVED** [review]
Fine, but this will break dictionay compression

**Pull request merged**
