### PR TITLE
fix #503

### LINKED ISSUE #503: parsed_yaml.js generator doesn't escape backticks
what the title says, this breaks the keyboard online

(created by emanresu A [here](https://chat.stackexchange.com/transcript/message/59983075))

### PR DESCRIPTION
**Pull request by Lyxal**
closes #503

### CODE REVIEW

**Comment by Lyxal** [comment]
this requires an immediate merge into prod btw

**Comment by chunkybanana** [comment]
Just use Vyxal's [`quotify`](https://github.com/Vyxal/Vyxal/blob/main/vyxal/elements.py#L2797)  - it's less likely to cause future bugs

**Comment by Lyxal** [comment]
> Just use Vyxal's [`quotify`](https://github.com/Vyxal/Vyxal/blob/main/vyxal/elements.py?rgh-link-date=2021-12-26T00%3A38%3A17Z#L2797) - it's less likely to cause future bugs

One small problem: the js generator is a few subdirectories down from the actual vyxal library.

**Comment by chunkybanana** [comment]
> > Just use Vyxal's [`quotify`](https://github.com/Vyxal/Vyxal/blob/main/vyxal/elements.py?rgh-link-date=2021-12-26T00%3A38%3A17Z#L2797) - it's less likely to cause future bugs
> 
> One small problem: the js generator is a few subdirectories down from the actual vyxal library.

Oh ok, nvm.

**Review by chunkybanana — APPROVED** [review]

**Review by pxeger — APPROVED** [review]

**Pull request merged**
