### PR TITLE
fix looping over the ghost variable

### LINKED ISSUE #617: Looping over the ghost variable is broken
# [Vyxal](https://github.com/Vyxal/Vyxal), 8 bytes
```
13 (| ←,
```
[Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCIxMyAofCDihpAsIiwiIiwiIl0=)

### PR DESCRIPTION
**Pull request by AMiller42**
fixes #617

### CODE REVIEW

**Review by chunkybanana — APPROVED** [review]

**Comment by pxeger** [comment]
Are there any other types of structure where this needs fixing too?

**Review by pxeger — APPROVED** [review]
otherwise LGTM

**Comment by AMiller42** [comment]
> Are there any other types of structure where this needs fixing too?

I don't know how necessary is, but for completeness' sake we should probably also fix this for calling functions, e.g. `@;`, since it currently does `VAR_()`

**Comment by cgccuser** [comment]
I'm just disabling auto merge so that someone can fix it for functions too (or someone could merge anyway if fixing it for functions is too much work rn)

**Comment by AMiller42** [comment]
I haven’t really looked at it yet, but if it’s anything like fixing it for loops, then it shouldn’t be too difficult.

**Review by Lyxal — APPROVED** [review]

**Pull request merged**
