### PR TITLE
Implement all indices

### LINKED ISSUE #971: add element to get all indices of an element
multidimensional would also be nice

(created by Steffan [here](https://chat.stackexchange.com/transcript/message/61112404))

### PR DESCRIPTION
**Pull request by cgccuser**
Will eventually close #971. Also modifies `enumerate_md` to act more like Python's enumerate (yields tuples `(index, item)` instead of just indices)

### CODE REVIEW

**Review by Lyxal — DISMISSED** [review]
Part 1 lgtm

**Review by Steffan153 — DISMISSED** [review]
Should we have a separate one for non-multi-dimensional?

**Comment by cgccuser** [comment]
@Steffan153 Sure

**Comment by cgccuser** [comment]
While this seems to work okay right now, `enumerate_md` is not safe to use with a finite list of infinite lists, let alone an infinite list of infinite lists. Once we get it working with infinite lists of infinite lists, implementing other builtins will also be easier.

**Review by Seggan — APPROVED** [review]
*pretends like I totally understood this*

**Review by Lyxal — APPROVED** [review]

**Pull request merged**
