### PR TITLE
3 words

### PR DESCRIPTION
**Pull request by Fmbalbuena**
3 words: Fmbalbuena, CGCC, TNB

### CODE REVIEW

**Review by pxeger — CHANGES_REQUESTED** [review]
You added these to the wrong dictionary. They should go into `contents`, not `small_dictionary`.

(going based on where similar ones like `pxeger` are)

**Review by Fmbalbuena — COMMENTED** [review]
Yes

**Comment by cgccuser** [comment]
I don't see much point to this, honestly. `TNB` and `CGCC` might be useful, but not `Fmbalbuena`. Also, the PR author hasn't made the changes yet and it doesn't seem like they will anytime soon.

**Comment by Fmbalbuena** [comment]
@cgccuser  Because I can't see the edit, can you reopen?

**Pull request closed without merging**
