### PR TITLE
run black on flask_app.py

### PR DESCRIPTION
**Pull request by pxeger**

### CODE REVIEW

**Comment by pxeger** [comment]
Just tried re-running the check, but of course the workflow changes from #286 don't apply here...

**Comment by pxeger** [comment]
probably should reorganise the imports in this as well, actually

**Review by cgccuser — APPROVED** [review]
I could've sworn I approved this already.

**Review by Lyxal — APPROVED** [review]

**Comment by Lyxal** [comment]
Note that I moved the version stuff fully inside the version route because it was causing errors when running the flask app locally

**Pull request merged**
