### PR TITLE
Fix #515

### LINKED ISSUE #515: Base-255 compression trims leading `a`s
When compressing a string using `øc`, or base-255 compression, any leading `a`s in the string are removed from the resulting string.

Example: [Try it Online!](https://vyxal.pythonanywhere.com/#WyIiLCIiLCJgcmlja3JvbGxgw7hjOiwgYGFhYWFhYWFhYWFhYWFhYWFyaWNrcm9sbGDDuGM6LCA9LCIsIiIsIiJd)

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #515

### CODE REVIEW

**Review by chunkybanana — APPROVED** [review]
This *will* invalidate all Vyxal 2.6 answers with compressed strings - right thing to do tho

**Comment by pxeger** [comment]
Can you add tests for this?

**Review by pxeger — CHANGES_REQUESTED** [review]
Can you add tests for this?

**Comment by Lyxal** [comment]
> Can you add tests for this?

That's what I'm currently working on

**Review by chunkybanana — APPROVED** [review]

**Review by cgccuser — APPROVED** [review]

**Pull request merged**
