### PR TITLE
Dyadic & triadic map

### PR DESCRIPTION
**Pull request by Steffan153**

### CODE REVIEW

**Review by Seggan — APPROVED** [review]
This is gonna be quite useful

**Comment by Steffan153** [comment]
sorry some of these tests are failing... ill fix that later

**Comment by Steffan153** [comment]
This doesn't quite yet close issue 494 as I need to do dyadic/triadic filter too

**Review by cgccuser — APPROVED** [review]
I agree with Seggan, very pogchamply of you or whatever it is gamers say

**Pull request merged**
