### PR TITLE
Fix ACE

### LINKED ISSUE #948: Fix the ACE that has been here since v2.7.2
The cop post is now safe, so we need to patch this now. Look in the security team for the explanation.

### PR DESCRIPTION
**Pull request by Steffan153**
Closes #948

### CODE REVIEW

**Review by Lyxal — APPROVED** [review]
You should probably get your git base sorted out lol

**Comment by Steffan153** [comment]
Lmao what in the world I dind't even notice that

I definitely checked out main this time

**Comment by Steffan153** [comment]
Should add auto-label for that

**Comment by Lyxal** [comment]
in the process of doing so now

**Review by cgccuser — APPROVED** [review]

**Pull request merged**
