### PR TITLE
Implement constant variables

### PR DESCRIPTION
**Pull request by Lyxal**

### CODE REVIEW

**Comment by Lyxal** [comment]
We may do a lot of goofy, but PR titles aren't typically goofy things.

**Comment by GingerIndustries** [comment]
💀

**Comment by Seggan** [comment]
... why. There'd literally be no point to this.

**Comment by Lyxal** [comment]
Constants help solidify the prac-lang side of vyxal which is something I want to invest in

**Comment by Steffan153** [comment]
There's plenty of prac-langs without constants

**Comment by Lyxal** [comment]
But the majority of the most popular ones (Java, Scala, C, C++, Rust, C#, JavaScript and more) do.

Constants provide programmer safety, which there isn't much of in a language like this. Every measure counts.

And it may be pointless for golfing, but for longer programs it's the same as using `val` for 40-50% of values in scala.

"But people won't use vyxal for longer programs" maybe, maybe not. I intend for people to be able to do so if they want, and I like having options available to make the prac-lang side something people won't complain about if they use it.

**Comment by Seggan** [comment]
🤷

**Review by GingerIndustries — APPROVED** [review]

**Pull request merged**
