### PR TITLE
Move code into a package

### PR DESCRIPTION
**Pull request by pxeger**
Not much of a proper refactor, just moving files around. I can't really test it that well atm so please let me know what needs to be fixed.

### CODE REVIEW

**Comment by Lyxal** [comment]
Some of the files seem a bit misplaced

**Comment by pxeger** [comment]
What do you mean by misplaced?

**Comment by Lyxal** [comment]
Nevermind, the test cases pass now 
For some reason, words.py was not being found

**Review by Lyxal — APPROVED** [review]
looks good to me. If it passes all the tests, and works with the flask app (which I tested myself), then I'm happy to merge

**Pull request merged**
