### PR TITLE
Fix `i` vectorise

### PR DESCRIPTION
**Pull request by AMiller42**
Fixes issue reported [here on Discord](https://discord.com/channels/936437703048822844/936444624493506610/1183850057393524818)

This is my first time editing any element functions, so please review before merging.

### CODE REVIEW

**Comment by lyxal** [comment]
Which bug report?

**Comment by AMiller42** [comment]
The first message in the channel. The error was due to `i` being given a list that has strings in it.

**Comment by lyxal** [comment]
> I got this error while interpreting:
`fizzbuzz FB## #?(ᶲkdFø, ##,##⟨h|t⟩∑⌊,_? ##→s s, _)`
with no flags on the Vyxal 3 online interpreter ([here](https://vyxal.github.io/latest.html))

I don't see any usage of `i` in that.

**Comment by lyxal** [comment]
And if you're referring to

```
vyxal.VList.index(https://vyxal.github.io/Vyxal/vyxal.js:78907:90)
```

in the error report, that's the index method of VList, not the index element

**Comment by AMiller42** [comment]
> > I got this error while interpreting:
> > `fizzbuzz FB## #?(ᶲkdFø, ##,##⟨h|t⟩∑⌊,_? ##→s s, _)`
> > with no flags on the Vyxal 3 online interpreter ([here](https://vyxal.github.io/latest.html))
> 
> I don't see any usage of `i` in that.

They weren't using any flags, so it was being interpreted as SBCS commands. In this case the issue could be boiled down to this: [Try it Online!](https://vyxal.github.io/latest.html#WyIiLCIiLCJmaSIsIiIsInN0cmluZ1xuYWxzbyBzdHJpbmciLCIzLjMuMCJd)

**Comment by AMiller42** [comment]
The line that's throwing the error is [this one](https://github.com/Vyxal/Vyxal/blob/version-3/shared/src/vyxal/Elements.scala#L1000C56-L1000C56), where if `b` is a list then it just assumes that it is a list of numbers, without actually doing any vectorisation. Adding proper vectorisation allows it to work with strings without modifying existing behavior.

**Review by lyxal — APPROVED** [review]

**Comment by lyxal** [comment]
Aha, I see the issue now. Merge when you're ready

**Pull request merged**
