### PR TITLE
Add partition after truthy indices and partition before indices elements

### LINKED ISSUE #1396: Add element to split a on truthy indices in b
05AB1E `Å¡`, Jelly `œṗ`. Also, split a on indices in b, Jelly `œṖ`.

### PR DESCRIPTION
**Pull request by Lyxal**
Closes #1396

### CODE REVIEW

**Review by Steffan153 — APPROVED** [review]

**Review by Steffan153 — COMMENTED** [review]
actually why do you have these as helper functions? no one's gonna use them as helpers

**Review by Steffan153 — CHANGES_REQUESTED** [review]
^ and also you ned to use `@lazylist_from` to make sure infinite list state is preserved.

**Comment by Lyxal** [comment]
> actually why do you have these as helper functions? no one's gonna use them as helpers

same could be said about half the functions in the file.

They are in the helper file just in case they need to be used for other split on functions - Jelly's are used for two different purposes, so I figured there could be more use cases.

**Review by Steffan153 — APPROVED** [review]
fine, but if we need them again, we could just move them to helpers when we actually need it.

**Review by PyGamer0 — APPROVED** [review]

**Pull request merged**
